### PR TITLE
Eleventy migration 

### PR DESCRIPTION
**Pull request by jasonwilliams**
This migrates to 11ty instead of Ruby.  With mermaid integration

### CODE REVIEW

**Comment by jasonwilliams** [comment]
in the end i used the graph from https://github.com/boa-dev/boa/pull/1921 but we will need a dark mode version

**Comment by Razican** [comment]
If we want to do this before the release (which makes sense if we want to first have the website and then the post), I would say that the release post shouldn't be included, right? And that should be a separate PR

**Comment by jasonwilliams** [comment]
I can remove the release post yeah, or if I include it I can remove the tag so it isn’t published

**Review by Razican — APPROVED** [review]
I switched dependabot to use the NPM package manager, and ran npm audit fix, to fix some vulnerabilities. Not all fixed, though. It's good for me :)

**Review by RageKnify — APPROVED** [review]

**Review by HalidOdat — APPROVED** [review]

**Pull request merged**
