### PR TITLE
Add aria-label and grid header on test hover

### PR DESCRIPTION
**Pull request by nekevss**
This is related to #148. Added the `aria-label` property so that it should display the title on hover. Tested on Firefox and Brave :smile:

### CODE REVIEW

**Review by HalidOdat — APPROVED** [review]
Nice addition!

**Comment by jedel1043** [comment]
Hmm, just wondering if this counts as misusing aria-label, since this is not using it for accessibility, but to implement a UX feature.

**Comment by nekevss** [comment]
That was mostly the idea of adding the aria-label for hover was for the accessibility, and hopefully to make the test grid more accessibility friendly.

There's a couple other approaches that I can think of off the top of my head: 

1. Add a card component that disables on hover for the tests. I'm not entirely sure if that's any friendlier accessibility wise.
2. Update the card header to include the test. I.e. Header: ArrayBuffer -> ArrayBuffer - name.js

**Review by jedel1043 — APPROVED** [review]
Liking the new test display on the header!

**Pull request merged**
